language: python

python:
  - "3.6"

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

env:
  global:
    - DJANGO=2.2 DB=postgres
    - DJANGO_SETTINGS_MODULE='cleanship.settings.ci'

services:
  - postgresql
    
before_script:
  - psql -c 'create database cleanship_test;' -U postgres
  - psql -c "create extension postgis" -d cleanship_test -U postgres

# install requirements
install:
  - pip install -r requirements/dev.txt
  - pip install coveralls

# To run tests
script:
  - coverage run manage.py test

# send coverage report to coveralls

after_success:
  - coveralls
