# Generated by Django 2.2.6 on 2019-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='authorEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
