# Generated by Django 2.2.6 on 2019-10-27 13:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_issue_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('id', 'name')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=mptt.fields.TreeForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.Category'),
            preserve_default=False,
        ),
    ]
