# Generated by Django 2.2.6 on 2019-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20191027_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
