# Generated by Django 2.2.6 on 2019-11-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20191102_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
