# Generated by Django 2.2.6 on 2019-11-03 17:12

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_issue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(choices=[(1, 'LOW'), (2, 'NORMAL'), (3, 'HIGH')], default=common.models.PriorityTypes(2)),
        ),
    ]
