# Generated by Django 2.2.6 on 2019-11-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='landowner',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
