# Generated by Django 2.2.6 on 2019-11-16 06:15

import common.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20191107_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'issue', 'verbose_name_plural': 'issues'},
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUBMITTED'), (2, 'WIP'), (3, 'SOLVED'), (4, 'IMPOSSIBLE'), (5, 'DUBLICATE')], default=common.models.StatusTypes(1), help_text='Stage of progress for the solution.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Short label of this category.', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent category within the hierachy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.Category', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned',
            field=models.ForeignKey(help_text='Responsible (internal) department, which processes the issue currently.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedIssues', to='auth.Group', verbose_name='assigned group'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='authorEmail',
            field=models.EmailField(help_text='eMail alias of the author.', max_length=254, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=mptt.fields.TreeForeignKey(help_text='Multi-level selection of which kind of note this issue comes closest.', on_delete=django.db.models.deletion.CASCADE, to='common.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of submission.', verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='delegated',
            field=models.ForeignKey(help_text='Responsible (external) organisation, which becomes involved in solving this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegatedIssues', to='auth.Group', verbose_name='delegated group'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(help_text='Notes describing further details.', max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='landowner',
            field=models.CharField(help_text='Operrator that manages the area of the position. (usually landowner, might be inaccurate)', max_length=250, null=True, verbose_name='landowner'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.CharField(help_text='Human readable description of the position.', max_length=150, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo that show the spot. (unprocessed, might include metadata)', null=True, upload_to='', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Georeference for this issue. (might be inaccurate)', srid=25833, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(choices=[(1, 'LOW'), (2, 'NORMAL'), (3, 'HIGH')], default=common.models.PriorityTypes(2), help_text='Importance of the note for responsibles.', verbose_name='priority'),
        ),
    ]
