# Generated by Django 2.2.6 on 2019-11-22 18:19

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20191116_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='published',
            field=models.BooleanField(default=False, help_text='If base information are currently public.', verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUBMITTED'), (2, 'WIP'), (3, 'SOLVED'), (4, 'IMPOSSIBLE'), (5, 'DUBLICATE')], default=common.models.StatusTypes(1), help_text='Stage of progress for the solution. (can be altered manually and by state changes)', verbose_name='status'),
        ),
    ]
