# Generated by Django 2.2.6 on 2019-11-23 19:23

import common.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20191122_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='published',
            field=models.BooleanField(default=False, help_text='If base information are currently public. (can be altered manually and by state changes)', verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUBMITTED'), (2, 'WIP'), (3, 'SOLVED'), (4, 'IMPOSSIBLE'), (5, 'DUBLICATE')], default=common.models.StatusTypes(1), help_text='Stage of progress for the solution.', verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Who wrote the content.', max_length=150, verbose_name='author')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When was the contet written.', verbose_name='creation date')),
                ('content', models.TextField(help_text='Text of the comment', max_length=500, verbose_name='content')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Issue')),
            ],
        ),
    ]
