# Generated by Django 2.2.6 on 2019-11-24 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20191123_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at', 'author'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When was the content written.', verbose_name='creation date'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorEmail', models.EmailField(help_text='eMail alias of the author (verified).', max_length=254, null=True, verbose_name='author')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When was the content written.', verbose_name='creation date')),
                ('content', models.TextField(help_text='Text of the feedback', max_length=500, verbose_name='content')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Issue')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at', 'authorEmail'],
            },
        ),
    ]
