# Generated by Django 2.2.6 on 2019-12-20 08:20

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20191129_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='authorTrust',
            field=models.IntegerField(choices=[(1, 'EXTERNAL'), (2, 'INTERNAL'), (3, 'FIELDTEAM')], default=common.models.TrustTypes(1), help_text='Trust level of the author.', verbose_name='trust'),
        ),
    ]
