# Generated by Django 2.2.6 on 2020-02-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20191221_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at', 'author_email'], 'verbose_name': 'feedback', 'verbose_name_plural': 'feedback'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='authorEmail',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='authorEmail',
            new_name='author_email',
        ),
    ]
