# Generated by Django 2.2.6 on 2020-02-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20200214_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='authorTrust',
            new_name='author_trust',
        ),
    ]
