# Generated by Django 2.2.6 on 2020-04-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20200329_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status_text',
            field=models.TextField(blank=True, help_text='Further details explaining the progress / plans / challanges / milestones / ... .', max_length=1000, null=True, verbose_name='status text'),
        ),
    ]
