# Generated by Django 2.2.6 on 2020-05-03 09:40

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20200422_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, help_text='Who wrote the content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When was the content written.', verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author_trust',
            field=models.IntegerField(choices=[(1, 'EXTERNAL'), (2, 'INTERNAL'), (3, 'FIELDTEAM')], default=common.models.TrustTypes(1), editable=False, help_text='Trust level of the author.', verbose_name='trust'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.CharField(blank=True, editable=False, help_text='Human readable description of the position.', max_length=150, null=True, verbose_name='location'),
        ),
    ]
